import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Epic Recipes Next App",
    description: "Generated by next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="h-10 bg-gray-800 dark:bg-slate-800 py-2 pe-2">
                    <p className="text-end text-slate-300 pt-1">
                        Call us: 081-234-5678
                    </p>
                </div>
                <div className="max-w-6xl mx-auto flex flex-col min-h-screen px-2">
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <Header />
                        <main>{children}</main>
                        <Footer />
                    </ThemeProvider>
                </div>
            </body>
        </html>
    );
}
